// Mocks generated by Mockito 5.4.4 from annotations
// in tick_task/test/repositories/task_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tick_task/src/core/rest_api/base_rest_api.dart' as _i2;
import 'package:tick_task/src/core/rest_api/rest_api.dart' as _i4;
import 'package:tick_task/src/core/rest_api/rest_api_response_data.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestApiAttributes_0 extends _i1.SmartFake
    implements _i2.RestApiAttributes {
  _FakeRestApiAttributes_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestApiResponseData_1<T1> extends _i1.SmartFake
    implements _i3.RestApiResponseData<T1> {
  _FakeRestApiResponseData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestApi extends _i1.Mock implements _i4.RestApi {
  MockRestApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestApiAttributes get appEndPoint => (super.noSuchMethod(
        Invocation.getter(#appEndPoint),
        returnValue: _FakeRestApiAttributes_0(
          this,
          Invocation.getter(#appEndPoint),
        ),
      ) as _i2.RestApiAttributes);

  @override
  set appEndPoint(_i2.RestApiAttributes? _appEndPoint) => super.noSuchMethod(
        Invocation.setter(
          #appEndPoint,
          _appEndPoint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<dynamic> get paths => (super.noSuchMethod(
        Invocation.getter(#paths),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  set paths(List<dynamic>? _paths) => super.noSuchMethod(
        Invocation.setter(
          #paths,
          _paths,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get queryParameters => (super.noSuchMethod(
        Invocation.getter(#queryParameters),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set queryParameters(Map<String, dynamic>? _queryParameters) =>
      super.noSuchMethod(
        Invocation.setter(
          #queryParameters,
          _queryParameters,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get requestParameters => (super.noSuchMethod(
        Invocation.getter(#requestParameters),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set requestParameters(dynamic parameters) => super.noSuchMethod(
        Invocation.setter(
          #requestParameters,
          parameters,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> getHeaders() => (super.noSuchMethod(
        Invocation.method(
          #getHeaders,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  String getUrl() => (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getUrl,
            [],
          ),
        ),
      ) as String);

  @override
  _i6.Future<_i3.RestApiResponseData<T>> execute<T>(
          {T Function(dynamic)? parser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#parser: parser},
        ),
        returnValue: _i6.Future<_i3.RestApiResponseData<T>>.value(
            _FakeRestApiResponseData_1<T>(
          this,
          Invocation.method(
            #execute,
            [],
            {#parser: parser},
          ),
        )),
      ) as _i6.Future<_i3.RestApiResponseData<T>>);

  @override
  _i6.Future<_i3.RestApiResponseData<List<T>>> executeForList<T>(
          {List<T> Function(List<dynamic>)? parser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeForList,
          [],
          {#parser: parser},
        ),
        returnValue: _i6.Future<_i3.RestApiResponseData<List<T>>>.value(
            _FakeRestApiResponseData_1<List<T>>(
          this,
          Invocation.method(
            #executeForList,
            [],
            {#parser: parser},
          ),
        )),
      ) as _i6.Future<_i3.RestApiResponseData<List<T>>>);
}
