// Mocks generated by Mockito 5.4.4 from annotations
// in tick_task/test/blocs/completed_task_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tick_task/src/data/model/task_response.dart' as _i4;
import 'package:tick_task/src/services/completed_tasks_storage.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CompletedTasksStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompletedTasksStorage extends _i1.Mock
    implements _i2.CompletedTasksStorage {
  MockCompletedTasksStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveCompletedTask(_i4.TodoistTaskResponseData? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCompletedTask,
          [task],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TodoistTaskResponseData>> getCompletedTasks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTasks,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TodoistTaskResponseData>>.value(
            <_i4.TodoistTaskResponseData>[]),
      ) as _i3.Future<List<_i4.TodoistTaskResponseData>>);

  @override
  _i3.Future<void> clearCompletedTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedTasks,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isTaskCompleted(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #isTaskCompleted,
          [taskId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveTaskCompletionTime(
    String? taskId,
    Duration? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTaskCompletionTime,
          [
            taskId,
            duration,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Duration?> getTaskCompletionTime(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskCompletionTime,
          [taskId],
        ),
        returnValue: _i3.Future<Duration?>.value(),
      ) as _i3.Future<Duration?>);
}
